# Generated by Django 4.2.10 on 2024-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VacancyData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("link", models.URLField(max_length=1500)),
                ("salary_min", models.IntegerField(blank=True, default=1, null=True)),
                ("salary_max", models.IntegerField(blank=True, default=1, null=True)),
                ("salary_avg", models.IntegerField(blank=True, default=1, null=True)),
                ("currency", models.CharField(default="руб.", max_length=10)),
            ],
            options={
                "verbose_name": "вакансия",
                "verbose_name_plural": "вакансии",
            },
        ),
    ]
