### PURCHESES


### GET. Просмотр всех своих покупок
GET http://localhost:8000/api/v1/purchases/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNjcwNzYyLCJpYXQiOjE3MTAxMzQ3NjIsImp0aSI6IjZmODZmOTczNDM1YjRiZThiNTllODgxMTk1YzFiYjY0IiwidXNlcl9pZCI6MX0.-WWtNdEfxZd8Yez_qBulanPYdqbLHSFaKhHPTF-sKJE


### GET. Просмотр своих покупок + описание курсов
GET http://localhost:8000/api/v1/purchases/?include[]=course.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp.......





### POST. Добавление курса в покупку. Покупка создается со статусом "CREATED". Перевод в статус "COMPLETED" происход только после оплаты курса.
POST http://localhost:8000/api/v1/purchases/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp.......
Content-Type: application/json

{
  "course_id": 1
}
