### ПРОСМОТР УРОКОВ (у тех курсов, которые я оплатил)


### GET. Показывает уроки только у купленных курсов со статусом "completed"
GET http://localhost:8000/api/v1/lessons/?include[]=comments.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNjcwNzYyLCJpYXQiOjE3MTAxMzQ3NjIsImp0aSI6IjZmODZmOTczNDM1YjRiZThiNTllODgxMTk1YzFiYjY0IiwidXNlcl9pZCI6MX0.-WWtNdEfxZd8Yez_qBulanPYdqbLHSFaKhHPTF-sKJE




### GET. Показывает Задания к Урокам только у купленных курсов со статусом "completed"
GET http://localhost:8000/api/v1/lesson-tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.......
