version: "3.8"

networks:
  private:

volumes:
  pg_data:

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
