### --------------------------------------НОВЫЕ ЗАПРОСЫ ------------------------------------------------








### --------------------------------------РЕАЛИЗОВАННЫЕ ЗАПРОСЫ ------------------------------------------------

# TOKEN

### Создать TOKEN для созданного Юзера
POST http://localhost:8000/api/v1/auth/jwt/create/
Content-Type: application/json

{
  "email": "admin@admin.org",
  "password": "admin"
}


### 1. COURSES

### Просмотр без авторизации выводится весь список действующих курсов, is_selible=True. При авторизации - добавляются те курсы, которые уже куплены текущим юзером)
GET http://localhost:8000/api/v1/courses/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNDk3MDA3LCJpYXQiOjE3MDk5NjEwMDcsImp0aSI6ImEwYjFkMjdjYzdiYjQxMzBhMzVmNjljZDk3YmQxNjI1IiwidXNlcl9pZCI6MX0.iX6GX4q6KuWs_nWFCptlUEgYZHRpi6GjIJtgQcETZMI


### ДИНАМИЧЕСКИЙ ПРОСМОТР с фильтрацией и исключением/добавлением полей:

### 1.1. Исключаем поле "description"
GET http://localhost:8000/api/v1/courses/?exclude[]=description
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE

### 1.2. Добавляем поле
GET http://localhost:8000/api/v1/courses/?exclude[]=description&include[]=lessons.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE


### 1.3. Добавляем вложенную группу Videos
GET http://localhost:8000/api/v1/courses/?include[]=lessons.videos.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE


### 1.4. Добавили вложенного автора
GET http://localhost:8000/api/v1/courses/?include[]=author.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE


### 1.5. Получить уроки
GET http://localhost:8000/api/v1/lessons/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE






###-----------------------------------------------------------------------

# 2. PURCHESES


### 2.1 Просмотр всех своих покупок
GET http://localhost:8000/api/v1/purchases/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE


### 2.2 Просмотр своих покупок + описание курсов
GET http://localhost:8000/api/v1/purchases/?include[]=course.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE


### 2.3 Добавление курса в покупку
POST http://localhost:8000/api/v1/purchases/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE
Content-Type: application/json

{
  "course_id": 2
}





###-----------------------------------------------------------------------


### 3. FAVOURITES (Избранное)- переключатель True/False. Работаем с конкретным объектом (Detail=True)

POST http://localhost:8000/api/v1/courses/1/toggle-favourite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE



###-----------------------------------------------------------------------


### 4. ПЛАТЕЖНЫЙ ШЛЮЗ.


### 4.1 Получение ссылки на оплату. Работаем с конкретным объектом
GET http://localhost:8000/api/v1/purchases/1/payment-link/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzY2ODY4LCJpYXQiOjE3MDg4MzA4NjgsImp0aSI6ImYxYTU3YzczODc2NzQ1MjQ5ODMwZWIzZDU1YWY0ZDdmIiwidXNlcl9pZCI6MX0.H1xGScreUgeD9nYlNza-eH4T6k6OsuuHbEkBZ5juBpE
Content-Type: application/json


### 4.2. Ответ от Leadpay со статусом (success / fail)
POST http://localhost:8000/api/v1/leadpay-notification/
Content-Type: application/json

{
  "status": "success",
  "summa": "10000",
  "order_id": "1"
}



###-----------------------------------------------------------------------


### 5. ПРОВЕРКА ЗАДАНИЙ.


### 5.1 Автопроверка (автотест) GET - list UserAnswer
GET http://localhost:8000/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNjQxNDg2LCJpYXQiOjE3MDkxMDU0ODYsImp0aSI6ImZlZjRkZGJmZmYwMTRmMTc4YTEwNWQwYjhmODFhZDNlIiwidXNlcl9pZCI6MX0.2gA_C5FJtqunaI0ytM_iQJH0TU7Iwf7-vsB62usDfBI


### 5.2 Автопроверка (автотест) POST - UserAnswer
POST http://localhost:8000/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNjQxNDg2LCJpYXQiOjE3MDkxMDU0ODYsImp0aSI6ImZlZjRkZGJmZmYwMTRmMTc4YTEwNWQwYjhmODFhZDNlIiwidXNlcl9pZCI6MX0.2gA_C5FJtqunaI0ytM_iQJH0TU7Iwf7-vsB62usDfBI
Content-Type: application/json

{
  "task": 1,
  "predefined_answers": [1, 2]
}


### 5.3 Ручная проверка POST - UserAnswer - custom
POST http://localhost:8000/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNjQxNDg2LCJpYXQiOjE3MDkxMDU0ODYsImp0aSI6ImZlZjRkZGJmZmYwMTRmMTc4YTEwNWQwYjhmODFhZDNlIiwidXNlcl9pZCI6MX0.2gA_C5FJtqunaI0ytM_iQJH0TU7Iwf7-vsB62usDfBI
Content-Type: application/json

{
  "task": 3,
  "custom_answer": "Мой ответ - вот такой"
}



###-----------------------------------------------------------------------


### 6. ПРОСМОТР УРОКОВ С ВАРИАНТАМИ ОТВЕТОВ


### 6.1 Показывает уроки только у купленных курсов со статусом completed

### LESSON
GET http://localhost:8000/api/v1/lessons/?include[]=comments.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNjQxNDg2LCJpYXQiOjE3MDkxMDU0ODYsImp0aSI6ImZlZjRkZGJmZmYwMTRmMTc4YTEwNWQwYjhmODFhZDNlIiwidXNlcl9pZCI6MX0.2gA_C5FJtqunaI0ytM_iQJH0TU7Iwf7-vsB62usDfBI


### TASK
GET http://localhost:8000/api/v1/lesson-tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNjQxNDg2LCJpYXQiOjE3MDkxMDU0ODYsImp0aSI6ImZlZjRkZGJmZmYwMTRmMTc4YTEwNWQwYjhmODFhZDNlIiwidXNlcl9pZCI6MX0.2gA_C5FJtqunaI0ytM_iQJH0TU7Iwf7-vsB62usDfBI




###-----------------------------------------------------------------------


### 7. ОТЗЫВЫ

### REVIEWS

GET http://localhost:8000/api/v1/reviews/?include[]=images.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNDk3MDA3LCJpYXQiOjE3MDk5NjEwMDcsImp0aSI6ImEwYjFkMjdjYzdiYjQxMzBhMzVmNjljZDk3YmQxNjI1IiwidXNlcl9pZCI6MX0.iX6GX4q6KuWs_nWFCptlUEgYZHRpi6GjIJtgQcETZMI


### CREATE REVIEW

POST http://localhost:8000/api/v1/reviews/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNDk3MDA3LCJpYXQiOjE3MDk5NjEwMDcsImp0aSI6ImEwYjFkMjdjYzdiYjQxMzBhMzVmNjljZDk3YmQxNjI1IiwidXNlcl9pZCI6MX0.iX6GX4q6KuWs_nWFCptlUEgYZHRpi6GjIJtgQcETZMI
Content-Type: application/json

{
  "course": 1,
  "text": "Отзыв на курс - хороший курс",
  "rating": 7,
  "images": ["8643bddc-3b6a-4403-962e-110011615326"]
}



###-----------------------------------------------------------------------




### 8. КОММЕНТАРИИ

### COMMENTS

GET http://localhost:8000/api/v1/comments/?include[]=images.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNDk3MDA3LCJpYXQiOjE3MDk5NjEwMDcsImp0aSI6ImEwYjFkMjdjYzdiYjQxMzBhMzVmNjljZDk3YmQxNjI1IiwidXNlcl9pZCI6MX0.iX6GX4q6KuWs_nWFCptlUEgYZHRpi6GjIJtgQcETZMI


### CREATE COMMENT

POST http://localhost:8000/api/v1/comments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNDk3MDA3LCJpYXQiOjE3MDk5NjEwMDcsImp0aSI6ImEwYjFkMjdjYzdiYjQxMzBhMzVmNjljZDk3YmQxNjI1IiwidXNlcl9pZCI6MX0.iX6GX4q6KuWs_nWFCptlUEgYZHRpi6GjIJtgQcETZMI
Content-Type: application/json

{
  "lesson": 1,
  "text": "хреновина хрен",
  "images": ["8643bddc-3b6a-4403-962e-110011615326"]
}

### Upload image

POST http://localhost:8000/api/v1/media/images/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNDk3MDA3LCJpYXQiOjE3MDk5NjEwMDcsImp0aSI6ImEwYjFkMjdjYzdiYjQxMzBhMzVmNjljZDk3YmQxNjI1IiwidXNlcl9pZCI6MX0.iX6GX4q6KuWs_nWFCptlUEgYZHRpi6GjIJtgQcETZMI
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Foto_image.png"
Content-Type: image/png

< /home/antuan/Desktop/Skillsup/skills_project/data_all/foto1.png
--WebAppBoundary--



### ДОПОЛНИТЕЛЬНО******************************************************************************


### Создание Юзера
POST http://localhost:8000/api/v1/users/
Content-Type: application/json

{
  "email": "admin10@admin.org",
  "password": "develop12345"
}


### Проверка данных Юзера
GET http://localhost:8000/api/v1/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNjQxNDg2LCJpYXQiOjE3MDkxMDU0ODYsImp0aSI6ImZlZjRkZGJmZmYwMTRmMTc4YTEwNWQwYjhmODFhZDNlIiwidXNlcl9pZCI6MX0.2gA_C5FJtqunaI0ytM_iQJH0TU7Iwf7-vsB62usDfBI

### Проверка самого Токена
https://jwt.io/



# Если работаем через Postman:
# https://skills-up.postman.co/workspace/skills-up~532ccf51-bc2b-4914-ac2d-6ad0831f096c/overview


# При работе через Swagger: http://127.0.0.1:8000/docs/swagger/
# Token для Swagger:        Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2j.......PDV34q7PrQ

###____________________________________________________________________________#
