### --------------------------------------НОВЫЕ ЗАПРОСЫ ------------------------------------------------








### --------------------------------------РЕАЛИЗОВАННЫЕ ЗАПРОСЫ ------------------------------------------------

# 1. COURSES

### Просмотр без авторизации выводится весь список действующих курсов, is_selible=True. При авторизации - добавляются те курсы, которые уже куплены текущим юзером)
GET http://79.174.93.205/api/v1/courses/
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I


### ДИНАМИЧЕСКИЙ ПРОСМОТР с фильтрацией и исключением/добавлением полей:

### 1.1. Исключаем поле "description"
GET http://79.174.93.205/api/v1/courses/?exclude[]=description
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I

### 1.2. Добавляем поле
GET http://79.174.93.205/api/v1/courses/?exclude[]=description&include[]=lessons.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I


### 1.3. Добавляем вложенную группу Videos
GET http://79.174.93.205/api/v1/courses/?include[]=lessons.videos.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I


### 1.4. Добавили вложенного автора
GET http://79.174.93.205/api/v1/courses/?include[]=author.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I


### 1.5. Получить уроки
GET http://79.174.93.205/api/v1/lessons/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I






###-----------------------------------------------------------------------

# 2. PURCHESES


### 2.1 Просмотр всех своих покупок
GET http://79.174.93.205/api/v1/purchases/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I


### 2.2 Просмотр своих покупок + описание курсов
GET http://79.174.93.205/api/v1/purchases/?include[]=course.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I


### 2.3 Добавление курса в покупку
POST http://79.174.93.205/api/v1/purchases/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I
Content-Type: application/json

{
  "course_id": 2
}





###-----------------------------------------------------------------------


### 3. FAVOURITES (Избранное)- переключатель True/False. Работаем с конкретным объектом (Detail=True)

POST http://79.174.93.205/api/v1/courses/1/toggle-favourite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I



###-----------------------------------------------------------------------


### 4. ПЛАТЕЖНЫЙ ШЛЮЗ.


### 4.1 Получение ссылки на оплату. Работаем с конкретным объектом
GET http://79.174.93.205/api/v1/purchases/1/payment-link/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I
Content-Type: application/json


### 4.2. Ответ от Leadpay со статусом (success / fail)
POST http://79.174.93.205/api/v1/leadpay-notification/
Content-Type: application/json

{
  "status": "success",
  "summa": "10000",
  "order_id": "1"
}



###-----------------------------------------------------------------------


### 5. ПРОВЕРКА ЗАДАНИЙ.


### 5.1 Автопроверка (автотест) GET - list UserAnswer
GET http://79.174.93.205/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I


### 5.2 Автопроверка (автотест) POST - UserAnswer
POST http://79.174.93.205/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I
Content-Type: application/json

{
  "task": 1,
  "predefined_answers": [1, 2]
}


### 5.3 Ручная проверка POST - UserAnswer - custom
POST http://79.174.93.205/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I
Content-Type: application/json

{
  "task": 3,
  "custom_answer": "Мой ответ - вот такой"
}



###-----------------------------------------------------------------------


### 6. ПРОСМОТР УРОКОВ С ВАРИАНТАМИ ОТВЕТОВ


### 6.1 Показывает уроки только у купленных курсов со статусом completed

### LESSON
GET http://79.174.93.205/api/v1/lessons/?include[]=comments.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I


### TASK
GET http://79.174.93.205/api/v1/lesson-tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I




###-----------------------------------------------------------------------


### 7. ОТЗЫВЫ

### REVIEWS

GET http://79.174.93.205/api/v1/reviews/?filter{course.id}=2

### CREATE REVIEW

POST http://79.174.93.205/api/v1/reviews/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I
Content-Type: application/json

{
  "course": 1,
  "text": "хреновый курс, блин блинский",
  "rating": 7
}



###-----------------------------------------------------------------------




### 8. КОММЕНТАРИИ

### COMMENTS

GET http://79.174.93.205/api/v1/comments/


### CREATE COMMENT

POST http://79.174.93.205/api/v1/comments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I
Content-Type: application/json

{
  "lesson": 1,
  "text": "хреновина хрен"
}




### ДОПОЛНИТЕЛЬНО******************************************************************************

# TOKEN

### Создать TOKEN для созданного Юзера
POST http://79.174.93.205/api/v1/auth/jwt/create/
Content-Type: application/json

{
  "email": "admin@admin.org",
  "password": "admin"
}



### Создание Юзера
POST http://79.174.93.205/api/v1/users/
Content-Type: application/json

{
  "email": "admin10@admin.org",
  "password": "develop12345"
}


### Проверка данных Юзера
GET http://79.174.93.205/api/v1/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMDY1NDk2LCJpYXQiOjE3MDk1Mjk0OTYsImp0aSI6IjQ3OTgyYTA5ZWQyZTQwY2Q4NDlhYmE3ZmY1YjVlNmMwIiwidXNlcl9pZCI6MX0.08Q7UtOYD3c9A486UPoJoRUSA63zNx77sKnV9Fgm06I

### Проверка самого Токена
https://jwt.io/



# Если работаем через Postman:
https://skills-up.postman.co/workspace/skills-up~532ccf51-bc2b-4914-ac2d-6ad0831f096c/overview


При работе через Swagger:
http://79.174.93.205/docs/swagger/

###____________________________________________________________________________#
