# Работаем через Postman.
# https://skills-up.postman.co/workspace/skills-up~532ccf51-bc2b-4914-ac2d-6ad0831f096c/overview

###  Создание Юзера
POST http://localhost:8000/api/v1/users/
Content-Type: application/json

{
  "email": "admin6@admin.org",
  "password": "develop12345"
}

### Создать TOKEN для Юзера
POST http://localhost:8000/api/v1/auth/jwt/create/
Content-Type: application/json

{
  "email": "admin5@admin.org",
  "password": "develop12345"
}

### Проверка данных Юзера
GET http://localhost:8000/api/v1/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1OTk2NjY1LCJpYXQiOjE3MDU5OTYzNjUsImp0aSI6ImVmYjUwNzVjMTEzMjQ3MTJiNTBkMzM4NzQxYjVkMzVhIiwidXNlcl9pZCI6Mn0.Uausx8_ximi1GMy4Qv9mcOAsBXyKClj-J5zKVyLceKc
