# Работаем через Postman.
# https://skills-up.postman.co/workspace/skills-up~532ccf51-bc2b-4914-ac2d-6ad0831f096c/overview

# 1. USER (создание, токен, проверка)

### Создание Юзера
POST http://localhost:8000/api/v1/users/
Content-Type: application/json

{
  "email": "admin10@admin.org",
  "password": "develop12345"
}

### Создать TOKEN для Юзера
POST http://localhost:8000/api/v1/auth/jwt/create/
Content-Type: application/json

{
  "email": "admin10@admin.org",
  "password": "develop12345"
}

### Проверка данных Юзера
GET http://localhost:8000/api/v1/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzkzMTM3LCJpYXQiOjE3MDYyNTcxMzcsImp0aSI6IjRlZGQzMDQzYjRjMDQxZWE4MzllNWE5NzM4MGNjOGFlIiwidXNlcl9pZCI6MTl9.j1vX6WJjow9NsxCkvThxNQ1fhQXSw4CkZT3sOy12M7s


### Проверка самого Токена
https://jwt.io/
#*********************************************************************************************



# 2. COURSES

###  Просмотр всех курсов
GET http://localhost:8000/api/v1/courses/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzkzMTM3LCJpYXQiOjE3MDYyNTcxMzcsImp0aSI6IjRlZGQzMDQzYjRjMDQxZWE4MzllNWE5NzM4MGNjOGFlIiwidXNlcl9pZCI6MTl9.j1vX6WJjow9NsxCkvThxNQ1fhQXSw4CkZT3sOy12M7s


###  Сортировка и Фильтрация курсов
GET http://localhost:8000/api/v1/courses/?ordering=price&product=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzkzMTM3LCJpYXQiOjE3MDYyNTcxMzcsImp0aSI6IjRlZGQzMDQzYjRjMDQxZWE4MzllNWE5NzM4MGNjOGFlIiwidXNlcl9pZCI6MTl9.j1vX6WJjow9NsxCkvThxNQ1fhQXSw4CkZT3sOy12M7s


### Загрузка файла
POST http://localhost:8000/api/v1/import/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzkzMTM3LCJpYXQiOjE3MDYyNTcxMzcsImp0aSI6IjRlZGQzMDQzYjRjMDQxZWE4MzllNWE5NzM4MGNjOGFlIiwidXNlcl9pZCI6MTl9.j1vX6WJjow9NsxCkvThxNQ1fhQXSw4CkZT3sOy12M7s


###
