# Generated by Django 4.2.10 on 2024-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pdf", models.FileField(max_length=500, upload_to="files/report/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
