# Generated by Django 4.2.10 on 2024-05-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city", models.CharField(max_length=100)),
                ("min_price", models.IntegerField()),
                ("max_price", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
