# Generated by Django 5.0.1 on 2024-01-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0003_remove_product_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="upc",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
