# Generated by Django 5.0.1 on 2024-01-11 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0004_course_upc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="upc",
        ),
    ]
