# Generated by Django 5.0.1 on 2024-01-11 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0006_course_upc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course_version",
            options={"verbose_name": "Версия курса", "verbose_name_plural": "Версии курса"},
        ),
    ]
