# Generated by Django 4.1.13 on 2024-03-07 08:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("holder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "направление/линейка курсов",
                "verbose_name_plural": "1. Направления/линейки курсов",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "комментарий",
                "verbose_name_plural": "5. Комментарии к урокам",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.PositiveIntegerField()),
                ("is_sellable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "2. Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("annotation", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "3. Уроки",
            },
        ),
        migrations.CreateModel(
            name="LessonTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("auto_test", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "задание по уроку",
                "verbose_name_plural": "3.1 Задания по уроку (Task)",
            },
        ),
        migrations.CreateModel(
            name="LessonTaskAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "вариант ответов",
                "verbose_name_plural": "Варианты ответов (predefined_answers)",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "линейка курсов",
                "verbose_name_plural": "линейки курсов",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("rating", models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "4. Отзывы к курсу",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("custom_answer", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="holder.imageholder",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="holder.linkholder",
                    ),
                ),
                (
                    "predefined_answers",
                    models.ManyToManyField(blank=True, related_name="+", to="courses.lessontaskanswer"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="courses.lessontask",
                    ),
                ),
            ],
            options={
                "verbose_name": "результат ответа",
                "verbose_name_plural": "3.2 Результаты ответов (UserAnswer)",
            },
        ),
    ]
