# Generated by Django 5.0.1 on 2024-01-18 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="favourites",
            field=models.ManyToManyField(blank=True, related_name="favourites", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="course",
            name="is_sellable",
            field=models.BooleanField(default=True),
        ),
    ]
