# Generated by Django 4.1.13 on 2024-03-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ("course", "order"), "verbose_name": "урок", "verbose_name_plural": "3. Уроки"},
        ),
        migrations.AddField(
            model_name="course",
            name="open_type",
            field=models.CharField(
                choices=[
                    ("instant", "Открывается сразу все при покупке"),
                    ("schedule", "Открывается по расписанию в уроках"),
                    ("progress", "Открывается по успешному прохождению предыдущего урока"),
                ],
                default="instant",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="open_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name="order"),
            preserve_default=False,
        ),
    ]
