# Generated by Django 4.1.13 on 2024-02-01 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_lesson_link_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
