# Generated by Django 4.1.13 on 2024-02-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0002_rename_video_link_video_file_remove_video_lessons"),
        ("courses", "0004_delete_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="videos",
            field=models.ManyToManyField(blank=True, related_name="+", to="holder.video"),
        ),
    ]
