# Generated by Django 4.1.13 on 2024-02-20 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0002_rename_video_link_video_file_remove_video_lessons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0005_lesson_videos"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("auto_test", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="courses.lesson"
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="holder.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonTaskAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possible_answers",
                        to="courses.lessontask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("custom_answer", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("success", models.BooleanField(default=False)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "predefined_answers",
                    models.ManyToManyField(blank=True, related_name="+", to="courses.lessontaskanswer"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="courses.lessontask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="holder.video",
                    ),
                ),
            ],
        ),
    ]
