# Generated by Django 4.1.13 on 2024-02-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0003_imageholder"),
        ("courses", "0006_lessontask_lessontaskanswer_useranswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessontaskanswer",
            name="value",
        ),
        migrations.AddField(
            model_name="lessontaskanswer",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="holder.imageholder",
            ),
        ),
        migrations.AddField(
            model_name="lessontaskanswer",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
