# Generated by Django 4.1.13 on 2024-02-21 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_remove_lessontaskanswer_value_lessontaskanswer_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "направление/линейка курсов",
                "verbose_name_plural": "1. Направления/линейки курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "курс", "verbose_name_plural": "2. Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "урок", "verbose_name_plural": "3. Уроки"},
        ),
        migrations.AlterModelOptions(
            name="lessontask",
            options={"verbose_name": "задание по уроку", "verbose_name_plural": "_ Задания по уроку (Д/З)"},
        ),
        migrations.AlterModelOptions(
            name="lessontaskanswer",
            options={"verbose_name": "ответ по Д/З", "verbose_name_plural": "_ Ответы по Д/З"},
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={"verbose_name": "результат ответа", "verbose_name_plural": "_ Результаты ответов"},
        ),
    ]
