# Generated by Django 4.1.13 on 2024-02-22 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0006_linkholder"),
        ("courses", "0009_remove_lessontask_video_lessontask_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessontask",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="lessontaskanswer",
            name="image",
        ),
        migrations.RemoveField(
            model_name="lessontaskanswer",
            name="video",
        ),
        migrations.AddField(
            model_name="lesson",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="+", to="holder.imageholder"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="links",
            field=models.ManyToManyField(blank=True, related_name="+", to="holder.linkholder"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessontask",
            name="links",
            field=models.ManyToManyField(blank=True, related_name="+", to="holder.linkholder"),
        ),
        migrations.AddField(
            model_name="lessontask",
            name="photos",
            field=models.ManyToManyField(blank=True, related_name="+", to="holder.imageholder"),
        ),
        migrations.AddField(
            model_name="lessontask",
            name="videos",
            field=models.ManyToManyField(blank=True, related_name="+", to="holder.videoholder"),
        ),
        migrations.AlterField(
            model_name="lessontaskanswer",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="holder.linkholder",
            ),
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
