# Generated by Django 4.1.13 on 2024-02-22 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_remove_lessontask_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="poster",
        ),
    ]
