# Generated by Django 4.1.13 on 2024-02-22 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_course_poster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessontask",
            old_name="photos",
            new_name="images",
        ),
    ]
