# Generated by Django 4.1.13 on 2024-02-22 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_rename_photos_lessontask_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useranswer",
            old_name="photo",
            new_name="image",
        ),
    ]
