version: "3.3"

networks:
  private:

volumes:
  pg_data:

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    networks:
      - private
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: antuanuran/skillsup:latest
    restart: always
    env_file:
      - .env
    networks:
      - private
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  worker:
    image: antuanuran/skillsup:latest
    restart: always
    env_file:
      - .env
    networks:
      - private
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    command: "celery -A skillsup worker"

  redis:
    image: redis:alpine
    networks:
      - private

  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - private
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/static
      - ./media:/var/media
    ports:
      - 8001:80
