# Generated by Django 4.1.13 on 2024-02-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistedWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "запрещенное слово",
                "verbose_name_plural": "запрещенные слова",
            },
        ),
    ]
