# Generated by Django 4.1.13 on 2024-02-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0004_delete_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("video_link", models.FileField(blank=True, max_length=500, null=True, upload_to="files/videos/")),
                ("lessons", models.ManyToManyField(blank=True, related_name="videos", to="courses.lesson")),
            ],
            options={
                "verbose_name": "видео-файл",
                "verbose_name_plural": "видео-файлы",
            },
        ),
    ]
