# Generated by Django 4.1.13 on 2024-02-01 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_link",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="video",
            name="lessons",
        ),
    ]
