# Generated by Django 4.1.13 on 2024-02-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0002_rename_video_link_video_file_remove_video_lessons"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageHolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.ImageField(max_length=500, upload_to="files/images/")),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
    ]
