# Generated by Django 4.1.13 on 2024-02-21 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_alter_category_options_alter_course_options_and_more"),
        ("holder", "0003_imageholder"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Video",
            new_name="VideoHolder",
        ),
    ]
