# Generated by Django 4.1.13 on 2024-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0004_rename_video_videoholder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoholder",
            name="file",
            field=models.FileField(max_length=500, upload_to="files/videos/"),
        ),
    ]
