# Generated by Django 4.1.13 on 2024-02-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holder", "0005_alter_videoholder_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkHolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link", models.URLField(max_length=500)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ссылка",
                "verbose_name_plural": "ссылки",
            },
        ),
    ]
