# Generated by Django 5.0.1 on 2024-01-10 08:50

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Администратор / Пользователь",
                "verbose_name_plural": "Администраторы / Пользователи",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
    ]
