### PURCHESES


### GET. Просмотр всех своих покупок
GET http://79.174.93.205/api/v1/purchases/
Authorization: Bearer {{token}}


### GET. Просмотр своих покупок + описание курсов
GET http://79.174.93.205/api/v1/purchases/?include[]=course.*
Authorization: Bearer {{token}}





### POST. Добавление курса в покупку. Покупка создается со статусом "CREATED". Перевод в статус "COMPLETED" происход только после оплаты курса.
POST http://79.174.93.205/api/v1/purchases/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "course_id": 1
}
