### FAVOURITES (Добавить конкретный курс в "Избранное"). Переключатель True/False. Работаем с конкретным объектом (Detail=True)

POST http://79.174.93.205/api/v1/courses/1/toggle-favourite/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXV.............
