### ПРОСМОТР УРОКОВ (у тех курсов, которые я оплатил)


### GET. Показывает уроки только у купленных курсов со статусом "completed"
GET http://79.174.93.205/api/v1/lessons/?include[]=comments.*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNjcyMTMwLCJpYXQiOjE3MTAxMzYxMzAsImp0aSI6IjVkNmFjMDliZmI0YjQzNjE5YTQyODBhNjgyNzZlOWE5IiwidXNlcl9pZCI6MX0.kSpE1Krf9_wZwGv8flxMBq8ROq3myxchGVgK7xV2Mr4




### GET. Показывает Задания к Урокам только у купленных курсов со статусом "completed"
GET http://79.174.93.205/api/v1/lesson-tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNjcyMTMwLCJpYXQiOjE3MTAxMzYxMzAsImp0aSI6IjVkNmFjMDliZmI0YjQzNjE5YTQyODBhNjgyNzZlOWE5IiwidXNlcl9pZCI6MX0.kSpE1Krf9_wZwGv8flxMBq8ROq3myxchGVgK7xV2Mr4
