### ПРОВЕРКА ЗАДАНИЙ



### GET. Просмотр всех своих ответов (тесты и развернутые ответы).
GET http://api.skillsup.fun/api/v1/user-answers/
Authorization: Bearer {{token}}



### 1. Тесты. POST. (Отправить свой ответ на Задание с вариантами, т.е. тесты)

### Отправить варианты ответов на Задание (тесты). После отправки ответа - придет автоматичесикй ответ и поменяется статус в зависимости от корректности / некорректности ответа.
POST http://api.skillsup.fun/api/v1/user-answers/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "task": 1,
  "predefined_answers": [1, 2]
}





### 2. Развернутый ответ. POST. (Отправить свой ответ на Задание без вариантов ответа). После того, как отправится ответ - задание улетит на проверку к Админу. И только после проверки, Админ поменяет статус на "провернно".

### "task" - обязательное поле, все остальные не обязательные.
### Если нужно прикрепить видео/фото/ссылку -> нужно скопировать uuid в предыдущем файле загрузки данных в Holder.
POST http://api.skillsup.fun/api/v1/user-answers/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "task": 3,
  "custom_answer": "Мой ответ - вот такой",
  "video": "fb9d8251-69a3-4320-87d4-cce9eaa58b4e",
  "link": "0a066ff6-e65f-4af6-89d8-e1a7d812c4c3",
  "image": "8804cb57-27d5-4ed2-91a5-9e22aa0e823d"
}
