### ПРОВЕРКА ЗАДАНИЙ



### GET. Просмотр всех своих ответов (тесты и развернутые ответы).
GET http://79.174.93.205/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6.................



### 1. Тесты. POST. (Отправить свой ответ на Задание с вариантами, т.е. тесты)

### Отправить варианты ответов на Задание (тесты). После отправки ответа - придет автоматичесикй ответ и поменяется статус в зависимости от корректности / некорректности ответа.
POST http://79.174.93.205/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6.................
Content-Type: application/json

{
  "task": 1,
  "predefined_answers": [1, 2]
}





### 2. Развернутый ответ. POST. (Отправить свой ответ на Задание без вариантов ответа). После того, как отправится ответ - задание улетит на проверку к Админу. И только после проверки, Админ поменяет статус на "провернно".

### "task" - обязательное поле, все остальные не обязательные.
### Если нужно прикрепить видео/фото/ссылку -> нужно скопировать uuid в предыдущем файле загрузки данных в Holder.
POST http://79.174.93.205/api/v1/user-answers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6.................
Content-Type: application/json

{
  "task": 3,
  "custom_answer": "Мой ответ - вот такой",
  "video": "c5bd3835-5292-42bb-8f47-428dc9de853e",
  "link": "ec537e98-b9eb-41ef-a1a5-ad3324cd6d86",
  "image": "8643bddc-3b6a-4403-962e-110011615326"
}
