### 1. ОТЗЫВЫ. REVIEWS

### GET. Просмотр всех отзывов к курсам.
GET http://79.174.93.205/api/v1/reviews/
Authorization: Bearer {{token}}




### POST. Создание нового отзыва к моему курсу (который оплачен, т.е. имеет статус - "Completed")
### Чтобы прикрепить картинку - нужно ее загрузить в Холдер и скопировать uuid
POST http://79.174.93.205/api/v1/reviews/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "course": 1,
  "text": "Отзыв на курс - хороший курс",
  "rating": 7,
  "images": ["8804cb57-27d5-4ed2-91a5-9e22aa0e823d"]
}





### 8. КОММЕНТАРИИ. COMMENTS

### GET. Просмотр всех комментариев к Уроком (lessons).
GET http://79.174.93.205/api/v1/comments/
Authorization: Bearer {{token}}


### POST. Создать комментарий. Комментировать может зарегистрированный пользователь. Но уроки может видеть только тот юзер, который купил курс. Соответственно комментировать может только уроки своего купленного курса.
### Чтобы прикрепить картинку - нужно ее загрузить в Холдер и скопировать uuid
POST http://79.174.93.205/api/v1/comments/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "lesson": 1,
  "text": "хреновина хрен хренский",
  "images": ["8804cb57-27d5-4ed2-91a5-9e22aa0e823d"]
}
