# Generated by Django 4.1.13 on 2024-03-07 08:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purchased_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("price", models.PositiveIntegerField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("CANCELED_BY_USER", "Canceled By User"),
                            ("CANCELED_BY_MANAGER", "Canceled By Manager"),
                            ("REFUND", "Refund"),
                            ("COMPLETED", "Completed"),
                            ("SUSPECTED", "Suspected"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="purchases", to="courses.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "покупка",
                "verbose_name_plural": "покупки",
            },
        ),
    ]
