# Generated by Django 4.1.13 on 2024-02-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CANCELED_BY_USER", "Canceled By User"),
                    ("CANCELED_BY_MANAGER", "Canceled By Manager"),
                    ("REFUND", "Refund"),
                    ("COMPLETED", "Completed"),
                    ("SUSPECTED", "Suspected"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
