# Generated by Django 4.1.13 on 2024-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_purchase_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(fields=("user", "course"), name="unique_course_per_user"),
        ),
    ]
