# Generated by Django 4.1.13 on 2024-02-12 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0003_purchase_unique_course_per_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkPay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="links_pays", to="purchases.purchase"
                    ),
                ),
            ],
        ),
    ]
