# Generated by Django 4.1.13 on 2024-02-15 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0004_linkpay"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LinkPay",
        ),
    ]
